name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        version: [16, 18, 20]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.version }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - run: npm ci

      - run: npm run lint

      - run: npm run test:e2e
