name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    strategy:
      matrix:
        version: [16, 18, 20]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.version }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Run npm ci
        run: npm ci

      - name: Run commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --verbose

      - name: Run npm run lint
        run: npm run lint

      - name: Run npm run test:e2e
        run: npm run test:e2e
